version: '3.3'
services:
  db:
    image: postgres:13
    volumes:
      - foodgramf:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: vzangiev/foodgram_backend
    volumes:
      - ../static/:/app/static/
      - media:/app/media/recipe/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    image: vzangiev/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ../static/:/var/html/static/
      - media:/var/html/media/recipe/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  foodgramf:
  static_value:
  media_value:
  media: