# Generated by Django 4.2.3 on 2023-08-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.CharField(help_text='Не больше 500 символов', max_length=500, verbose_name='Ваш рецепт'),
        ),
    ]
